import { EOL } from "os";
import { AxesArray, ConfigParams, Dialogue, PositionCoors, VariationAxes } from "./types.js";
import { Font } from "fontkit";
import { booleanToAss, colorToAss, round } from "./utils.js";
import { encode } from "uuencode4ass";
import subsetFont from "subset-font";
import { VideoSubs } from "./VideoSubs.js";
import { error } from "./log.js";
import { PKG_HOMEPAGE, PKG_VERSION } from "./package.js";

export async function compileAss(
  resX: number,
  resY: number,
  matrix: string,
  font: Font,
  fontBuffer: Buffer,
  params: ConfigParams,
  subs: VideoSubs,
  variationAxes: VariationAxes,
  embedFont: boolean,
) {
  let assData = "";
  function addLine(line: string) {
    assData += line + EOL;
  }

  addLine("\ufeff[Script Info]");
  addLine(`; Script generated by ASS Furiganizer v${PKG_VERSION}`);
  addLine(`; ${PKG_HOMEPAGE}`);
  if (!embedFont) {
    addLine(`;          This file requires font ${font.fullName}`);
    addLine("; WARNING  It was not embedded into this file");
    addLine(";          It must be installed for the subtitles to be displayed correctly");
  }
  addLine("ScriptType: v4.00+");
  addLine("LayoutResX: " + resX);
  addLine("LayoutResY: " + resY);
  addLine("PlayResX: " + resX);
  addLine("PlayResY: " + resY);
  addLine("ScaledBorderAndShadow: yes");
  addLine("YCbCr Matrix: " + matrix);
  addLine("");
  addLine("[V4+ Styles]")
  addLine("Format: Name, Fontname, Fontsize, PrimaryColour, " +
    "SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, " +
    "StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, " +
    "Shadow, Alignment, MarginL, MarginR, MarginV, Encoding");

  function getTagBlock(tags: string[]) {
    return "{" + tags.map(tag => `\\${tag}`).join("") + "}";
  }
  function appendAdditionalStyles(
    tags: string[],
    blur: number | undefined,
    shadowDirection: AxesArray | undefined
  ) {
    if (blur) {
      tags.push(`blur${blur}`);
    }
    if (shadowDirection) {
      const [x, y] = shadowDirection;
      if (x !== 0 || y !== 0) {
        tags.push(`xshad${x}`);
        tags.push(`yshad${y}`);
      }
    }
  }
  function getOpaqueBoxLine(
    data: string,
    blur: number | undefined,
    shadowDirection: AxesArray | undefined,
  ) {
    const tags = ["p1"];
    appendAdditionalStyles(tags, blur, shadowDirection);
    return getTagBlock(tags) + data + getTagBlock(["p0"]);
  }
  function getDialogueTagBlock(
    coors: PositionCoors,
    blur: number | undefined,
    shadowDirection: AxesArray | undefined,
    dialogue: Dialogue,
  ) {
    const tags: string[] = [];
    let { x, y } = coors;
    if (!isFinite(x) || !isFinite(y)) {
      let dialogueText =
        dialogue.lines.map(line => line.map(chunk => chunk.text)).join("↵");
      const PRINT_CHARS = 10;
      if (dialogueText.length > PRINT_CHARS) {
        dialogueText = dialogueText.slice(0, PRINT_CHARS);
        if (dialogueText[PRINT_CHARS - 1] === "↵") {
          dialogueText = dialogueText.slice(0, PRINT_CHARS - 1);
        }
        dialogueText += "...";
      }
      throw (
        "could not correctly calculate all the positions for Dialogue: " +
        `${dialogue.startTime}, '${dialogueText}'`
      )
    }
    tags.push(`pos(${round(x)},${round(y)})`);
    appendAdditionalStyles(tags, blur, shadowDirection);
    return getTagBlock(tags);
  }
  function addStyleLine(values: any[]) {
    addLine("Style: " + values.join(","));
  }
  function addDialogueLine(values: any[]) {
    addLine("Dialogue: " + values.join(","));
  }
  const TEXT_STYLE_NAME = "Text";
  const FURIGANA_STYLE_NAME = "Furigana";
  const OPAQUE_BOX_STYLE_NAME = "Background";
  const SECONDARY_COLOR = "&H000000FF";
  let style = params.styles.text;
  addStyleLine([
    TEXT_STYLE_NAME, font.fullName, round(style.fontsize),
    colorToAss(style.color), SECONDARY_COLOR, colorToAss(style.outline_color),
    colorToAss(style.shadow_color), booleanToAss(style.bold),
    booleanToAss(style.italic), 0, 0, 100, 100, 0, 0, 1,
    round(style.outline), round(style.shadow),
    7, 0, 0, 0, 1
  ])
  style = params.styles.furigana;
  addStyleLine([
    FURIGANA_STYLE_NAME, font.fullName, round(style.fontsize),
    colorToAss(style.color), SECONDARY_COLOR, colorToAss(style.outline_color),
    colorToAss(style.shadow_color), booleanToAss(style.bold),
    booleanToAss(style.italic), 0, 0, 100, 100, 0, 0, 1,
    round(style.outline), round(style.shadow),
    7, 0, 0, 0, 1
  ])
  if (params.styles.opaque_box?.enable) {
    const style = params.styles.opaque_box;
    addStyleLine([
      OPAQUE_BOX_STYLE_NAME, , 0, colorToAss(style.color),
      SECONDARY_COLOR, colorToAss(style.outline_color),
      colorToAss(style.shadow_color), 0, 0, 0, 0, 100, 100, 0, 0, 1,
      round(style.outline), round(style.shadow),
      7, 0, 0, 0, 1
    ])
  }

  if (embedFont) {
    addLine("");
    addLine("[Fonts]");
    addLine("fontname: " + font.fullName.replace(/[\s_]/g, "-").toLowerCase());

    let subsetFontBuffer: Buffer;
    try {
      subsetFontBuffer = await subsetFont(
        fontBuffer,
        subs.getCharset(),
        { variationAxes }
      );
    } catch (e: any) {
      error(e.message, "subset-font");
      throw (
        "could not create font subset. Please use another " +
        "font or pass --no-embed-font"
      );
    }
    addLine(encode(subsetFontBuffer));
  }

  addLine("");
  addLine("[Events]");
  addLine(
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, " +
    "MarginV, Effect, Text"
  );

  function formatText(text: string) {
    return text
      .replace(/ /g, "\\h")
      .replace(/[{}]/g, "\\$&");
  }

  // prevent shadow overlap
  let chunksReversed = false;
  if (
    params.styles.shadow_direction?.text &&
    params.styles.shadow_direction.text[0] < 0
  ) {
    chunksReversed = true;
  }

  for (const dialogue of subs.dialogues) {
    const { startTime, endTime, lines } = dialogue;
    for (const line of lines) {
      for (let i = 0; i < line.length; i++) {
        const chunk = line[chunksReversed ? Math.abs(i - line.length + 1) : i];
        addDialogueLine([
          1, startTime, endTime, TEXT_STYLE_NAME, , 0, 0, 0, ,
          getDialogueTagBlock(
            chunk.position.text,
            params.styles.blur?.text,
            params.styles.shadow_direction?.text,
            dialogue,
          ) + formatText(chunk.text)
        ]);
        if (chunk.furigana) {
          addDialogueLine([
            2, startTime, endTime, FURIGANA_STYLE_NAME, , 0, 0, 0, ,
            getDialogueTagBlock(
              chunk.position.furigana,
              params.styles.blur?.furigana,
              params.styles.shadow_direction?.furigana,
              dialogue,
            ) + formatText(chunk.furigana)
          ]);
        }
      }
    }
    if (params.styles.opaque_box?.enable) {
      addDialogueLine([
        0, startTime, endTime, OPAQUE_BOX_STYLE_NAME, , 0, 0, 0, ,
        getOpaqueBoxLine(
          dialogue.opaqueBox,
          params.styles.blur?.opaque_box,
          params.styles.shadow_direction?.opaque_box,
        )
      ]);
    }
  }

  return assData;
}